### ISSUE TITLE
Comparing Multiple Loans

### ISSUE THREAD

**Issue by ataylor504** [wshep17/RegionsBank-JIC-101#51]
As a user I want to be able to compare the loans that I have favorited, so that I can see from a bird’s eye view what my options are.
We should be able to cache the data from different loan calculators so that upon refreshing the page the information stays in tact.
we should be able to display multiple charts

**Comment by Hilary325** [comment]
If you need to compare the loans, it is possible to use a loan payments calculator. You can evaluate loan term, optimal interest rate, and your own capabilities. After comparing all these factors, it will be easier to make the right decision.
